file(READ "${VERTEX_SHADER}" VERTEX_HEX HEX)
file(READ "${FRAGMENT_SHADER}" FRAGMENT_HEX HEX)
file(READ "${TEMPORAL_LUMA_SHADER}" TEMPORAL_LUMA_HEX HEX)
file(READ "${TEMPORAL_DOWNSAMPLE_SHADER}" TEMPORAL_DOWNSAMPLE_HEX HEX)
file(READ "${TEMPORAL_FLOW_SHADER}" TEMPORAL_FLOW_HEX HEX)
file(READ "${TEMPORAL_FIT_SHADER}" TEMPORAL_FIT_HEX HEX)

string(REGEX REPLACE "(..)" "0x\\1," VERTEX_BYTES "${VERTEX_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," FRAGMENT_BYTES "${FRAGMENT_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," TEMPORAL_LUMA_BYTES "${TEMPORAL_LUMA_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," TEMPORAL_DOWNSAMPLE_BYTES "${TEMPORAL_DOWNSAMPLE_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," TEMPORAL_FLOW_BYTES "${TEMPORAL_FLOW_HEX}")
string(REGEX REPLACE "(..)" "0x\\1," TEMPORAL_FIT_BYTES "${TEMPORAL_FIT_HEX}")

file(WRITE "${OUTPUT_HEADER}" "#pragma once\n")
file(APPEND "${OUTPUT_HEADER}" "#include <cstdint>\n\n")
file(APPEND "${OUTPUT_HEADER}" "namespace armakeup::shaders {\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kCameraVertex[] = {${VERTEX_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kCameraFragment[] = {${FRAGMENT_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kTemporalLuma[] = {${TEMPORAL_LUMA_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kTemporalDownsample[] = {${TEMPORAL_DOWNSAMPLE_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kTemporalFlow[] = {${TEMPORAL_FLOW_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "alignas(4) inline constexpr std::uint8_t kTemporalFit[] = {${TEMPORAL_FIT_BYTES}};\n")
file(APPEND "${OUTPUT_HEADER}" "}  // namespace armakeup::shaders\n")
